### ISSUE TITLE
Allow filters to be callable.

### ISSUE THREAD

**Issue by charettes** [akaariai/django-reverse-unique#10]
Passing callable arguments to queryset is deprecated as of Django 1.9.

Filters such as `Q(lang=get_language)` or `Q(from_date__lte=date.today)` are no longer valid.

We should allow the `filters` kwarg to be a `callable`,

```python
def get_active_translation_filters():
    return Q(lang=get_language())

active_translation = ReverseUnique(
    'ArticleTranslation', filters=get_active_translation_filters
)
```

**Comment by charettes** [comment]
Leaving an open issue for now since I don't have time to work on this ATM.

**Comment by akaariai** [comment]
This is now implemented (in https://github.com/akaariai/django-reverse-unique/commit/1b00ad6cfb3203272f893f553d60f52f7abd4929)
