### ISSUE TITLE
Make this a proper Python package

### ISSUE THREAD

**Issue by akaariai** [akaariai/django-reverse-unique#4]
I'd like to do three things:
  - Place this under different github account (so that changing the maintainer will be easy)
  - Create proper documentation (I haven't ever done this for any package, so pointers welcome)
  - Create a pypi package

CI-tests would be nice, too.

As said above I haven't done a package before, so if somebody has some experience of how to do the above mentioned things, I'm all ears.

**Comment by charettes** [comment]
I can deal with packaging and CI if you want. Not sure about the different Github account however.

**Comment by akaariai** [comment]
Cool. Lets forget about the different account for now.

**Comment by charettes** [comment]
See #5 for Django 1.7+ support, Tox and coverage, TravisCI and Coveralls.

**Comment by akaariai** [comment]
Done. Huge thanks to @charettes .
